name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: "mabenan/ServerManagerUI"
        version: "latest"
        file: "web.zip"
        target: "web.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: unzip web.zip -d tmp
    - run: mkdir public
    - run: cp -r tmp/build/web/* public
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mabenan/servermanager:$(date +%s)
