name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: "mabenan/ServerManagerUI"
        version: "latest"
        file: "web.zip"
        target: "web.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: unzip web.zip -d tmp
    - run: mkdir public
    - run: cp -a -r tmp/build/web/. public
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mabenan/servermanager:latest
